# This is a basic workflow to help you get started with Actions

name: Build and test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'openjdk'
          java-version: '15'
          check-latest: true
      - name: Assemble
        run: ./gradlew assemble
      - name: Java version
        run: java -version
      - name: Test
        run: ./gradlew jacocoTestReport
      - name: Submit report
        run: bash <(curl -s https://codecov.io/bash)

